<?php

$title = 'My albums';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<?php
$search = $form->get('search');
$search->setAttribute('class', 'form-control');
$search->setAttribute('placeholder', 'Search');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', [
    'action' => 'index',
]));
$form->prepare();
?>

<?= $this->form()->openTag($form) ?>

<div class="form-group">
    <?= $this->formElement($search) ?>
    <?= $this->formElementErrors()->render($search, ['class' => 'help-block']) ?>
</div>

<?= $this->formSubmit($submit) ?>

<?= $this->form()->closeTag() ?>

<p class="text-right">
    <a title="Add Album" class="btn btn-success btn-sm" href="<?= $this->url('album', ['action' => 'add']) ?>">
    <span class="glyphicon glyphicon-plus-sign"></span> Add</a>
</p>

<table class="table table-striped">
<thead>
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th></th>
    </tr>
</thead>
<?php if (isset($this->paginator) && $this->paginator->count() > 0): ?>
<?php foreach ($this->paginator as $album): ?>
    <tr>
        <td><?= $this->escapeHtml($album->title) ?></td>
        <td><?= $this->escapeHtml($album->artist) ?></td>
        <td class="text-right">
            <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>" 
               class="btn-info btn-sm" 
               title="Edit Album">
                <span class="glyphicon glyphicon-edit"></span>
            </a>&nbsp;
            <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>"
               class="btn-danger btn-sm"
               title="Delete Album">
                <span class="glyphicon glyphicon-remove-circle"></span>
            </a>
        </td>
    </tr>
<?php endforeach; ?>
<?php endif; ?>
</table>
<?php if (isset($this->paginator) && $this->paginator->count() > 0): ?>
<?= $this->paginationControl(
    // The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'album']
) ?>
<?php endif; ?>
